FROM node:6

WORKDIR /opt/ve
COPY . /opt/ve

# Configures git to use https:// instead of git:// 
RUN git config --global url."https://".insteadOf git://

# Install dependencies
RUN npm install 
RUN node ./node_modules/node-sass/scripts/install.js
RUN npm rebuild node-sass

# When the container runs, we run grunt. The second argument should reference a 
# server defined in the angular-mms-grunt-servers.json file. 
RUN ./node_modules/grunt/bin/grunt --ARTIFACTORY_URL="https://cae-artifactory.jpl.nasa.gov" --ARTIFACTORY_USER=$ARTIFACTORY_USER --ARTIFACTORY_PASSWORD=$ARTIFACTORY_PASSWORD --SNAPSHOT_REPO=maven-libs-snapshot-local --RELEASE_REPO=maven-libs-release-local --GROUP_ID=gov.nasa.jpl.cae deploy --verbose