[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ve_docs"
authors = [{name = "OpenMBEE Community", email = "openmbee@gmail.com"}]
dynamic = ["version", "description"]
