import { IButtonBarButton } from '@ve-core/button-bar';

export const search_default_buttons: IButtonBarButton[] = [
    {
        selectable: false,
        toggleable: true,
        tooltip: 'Documents',
        buttonId: 'search-filter-document',
        icon: 'item-type-document',
        //type: 'Document',
    },
    // { display: "Sections/Views", icon: null, //type: "View", "Section" },
    {
        selectable: false,
        toggleable: true,
        tooltip: 'Text',
        buttonId: 'search-filter-paragraph',
        icon: 'pe-type-paragraph',
        //type: 'Paragraph',
    },
    {
        selectable: false,
        toggleable: true,
        tooltip: 'Tables',
        buttonId: 'search-filter-table',
        icon: 'pe-type-table',
        //type: 'Table',
    },
    {
        selectable: false,
        toggleable: true,
        tooltip: 'Images',
        buttonId: 'search-filter-image',
        icon: 'pe-type-image',
        //type: 'Image',
    },
    {
        selectable: false,
        toggleable: true,
        tooltip: 'Equations',
        buttonId: 'search-filter-equation',
        icon: 'pe-type-equation',
        //type: 'Equation',
    },
    {
        selectable: false,
        toggleable: true,
        tooltip: 'Comments',
        buttonId: 'search-filter-comment',
        icon: 'pe-type-comment',
        //type: 'Comment',
    },
    {
        selectable: false,
        toggleable: true,
        tooltip: 'Sections',
        buttonId: 'search-filter-section',
        icon: 'pe-type-section',
        //type: 'Section',
    },
    {
        selectable: false,
        toggleable: true,
        tooltip: 'Views',
        buttonId: 'search-filter-view',
        icon: 'pe-type-view',
        //type: 'View',
    },
    {
        selectable: false,
        toggleable: true,
        tooltip: 'Requirements',
        buttonId: 'search-filter-req',
        icon: 'pe-type-req',
        //type: 'Requirement',
    },
];
