import { IButtonBarButton } from '@ve-core/button-bar'

export const pane_center_buttons: IButtonBarButton[] = [
    {
        id: 'show-edits',
        icon: 'fa-regular fa-pen-to-square',
        selectable: false,
        permission: true,
        tooltip: 'Enable Edits (alt + d)',
        spinner: false,
        toggleable: true,
        toggle_tooltip: 'Disable Edits (alt + d)',
    },
    {
        id: 'show-elements',
        icon: 'fa-brands fa-codepen',
        selectable: false,
        permission: true,
        tooltip: 'Show Elements (alt + e)',
        spinner: false,
        toggleable: true,
        toggle_tooltip: 'Hide Elements (alt + e)',
    },
    {
        id: 'show-comments',
        icon: 'fa-regular fa-comment',
        selectable: false,
        permission: true,
        tooltip: 'Show Comments (alt + c)',
        spinner: false,
        toggleable: true,
        toggle_tooltip: 'Hide Comments (alt + c)',
    },
    {
        id: 'show-numbering',
        icon: 'fa-solid fa-list-ol',
        selectable: false,
        permission: true,
        tooltip: 'Hide Numbering',
        spinner: false,
        toggleable: true,
        toggle_stack: true,
        toggle_tooltip: 'Show Numbering',
    },
    {
        id: 'refresh-numbering',
        icon: 'fa-solid fa-sort-numeric-asc',
        selectable: false,
        permission: true,
        tooltip: 'Refresh Figure Numbering',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'share-url',
        icon: 'fa-solid fa-arrow-up-right-from-square',
        selectable: false,
        permission: true,
        tooltip: 'Share Short URL',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'center-previous',
        icon: 'fa-solid fa-chevron-left',
        selectable: false,
        permission: true,
        tooltip: 'Previous (alt + ,)',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'center-next',
        icon: 'fa-solid fa-chevron-right',
        selectable: false,
        permission: true,
        tooltip: 'Next (alt + .)',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'export',
        icon: 'fa-solid fa-download',
        selectable: false,
        permission: true,
        tooltip: 'Export',
        button_content: 'Export',
        spinner: false,
        toggleable: true,
        dropdown_ids: ['word', 'tabletocsv'],
        dropdown_toggleable: true,
        dropdown_icon: 'fa-solid fa-caret-down',
        dropdown_toggle_icon: 'fa-solid fa-caret-up',
    },
    {
        id: 'print',
        icon: 'fa-solid fa-print',
        selectable: false,
        permission: true,
        tooltip: 'Print',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'convert-pdf',
        icon: 'fa-regular fa-file-pdf',
        selectable: false,
        permission: true,
        tooltip: 'Export to PDF',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'word',
        icon: 'fa-regular fa-file-word',
        selectable: false,
        permission: true,
        tooltip: 'Export to Word',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'tabletocsv',
        icon: 'fa-solid fa-table',
        selectable: false,
        permission: true,
        tooltip: 'Table to CSV',
        spinner: false,
        toggleable: false,
    },
]
