import { TButton } from './content-tool'

export const default_toolbar_buttons: TButton[] = [
    {
        id: 'content-viewer',
        category: 'document',
        icon: 'fa-eye',
        selected: true,
        active: true,
        permission: true,
        tooltip: 'Preview Element',
        spinner: false,
        dynamic_ids: ['content-editor-saveall'],
        enabledFor: ['main'],
    },
    {
        id: 'content-history',
        category: 'global',
        icon: 'fa-history',
        selected: false,
        active: true,
        permission: true,
        tooltip: 'Element History',
        spinner: false,
        dynamic_ids: ['content-editor-saveall'],
    },
    {
        id: 'content-history',
        category: 'document',
        icon: 'fa-edit',
        selected: false,
        active: true,
        permission: false,
        tooltip: 'Edit Element',
        spinner: false,
        dynamic_ids: [
            'content-editor-save',
            'content-editor-saveC',
            'content-editor-saveall',
            'content-editor-cancel',
        ],
    },
    {
        id: 'content-reorder',
        category: 'global',
        icon: 'fa-arrows-v',
        selected: false,
        active: true,
        permission: false,
        tooltip: 'Reorder Content',
        spinner: false,
        dynamic_ids: ['content-reorder-save', 'content-reorder-cancel'],
        enabledFor: ['main.project.ref.preview', 'main.project.ref.document'],
    },
    {
        id: 'content-tags',
        category: 'document',
        icon: 'fa-code-fork',
        selected: false,
        active: true,
        permission: true,
        tooltip: 'Branches and Tags',
        spinner: false,
    },
]

export const default_dynamic_buttons: TButton[] = [
    {
        id: 'content-editor-save',
        category: 'dynamic',
        icon: 'fa-save',
        dynamic: true,
        selected: false,
        active: false,
        permission: true,
        tooltip: 'Save',
        spinner: false,
    },
    {
        id: 'content-editor-saveC',
        category: 'dynamic',
        icon: 'fa-send-o',
        dynamic: true,
        selected: false,
        active: false,
        permission: true,
        tooltip: 'Save and Continue',
        spinner: false,
    },
    {
        id: 'content-editor-saveall',
        category: 'dynamic',
        icon: 'fa-save-all',
        dynamic: true,
        selected: false,
        active: false,
        permission: false,
        tooltip: 'Save All (alt + a)',
        spinner: false,
    },
    {
        id: 'content-editor-cancel',
        category: 'dynamic',
        icon: 'fa-times',
        dynamic: true,
        selected: false,
        active: false,
        permission: true,
        tooltip: 'Cancel',
        spinner: false,
    },
    {
        id: 'content-reorder-save',
        category: 'dynamic',
        icon: 'fa-save',
        dynamic: true,
        selected: false,
        active: false,
        permission: true,
        tooltip: 'Save',
        spinner: false,
    },
    {
        id: 'content-reorder-cancel',
        category: 'dynamic',
        icon: 'fa-times',
        dynamic: true,
        selected: false,
        active: false,
        permission: true,
        tooltip: 'Cancel',
        spinner: false,
    },
]
