import { IButtonBarButton } from '@ve-core/button-bar'
import { IToolBarButton } from '@ve-core/toolbar'

export const trees_default_toolbar: IToolBarButton[] = [
    {
        id: 'tree-of-favorites',
        icon: 'fa-star',
        selected: false,
        active: false,
        permission: true,
        tooltip: 'Favorite Documents',
        spinner: false,
        category: 'portal',
        enabledFor: ['**.portal.**'],
    },
    {
        id: 'tree-of-documents',
        icon: 'fa-folder-tree',
        selected: true,
        active: true,
        permission: true,
        tooltip: 'Project Document Tree',
        spinner: false,
        enabledFor: ['**.portal.**'],
    },
    {
        id: 'tree-of-contents',
        icon: 'fa-folder-tree',
        selected: true,
        active: false,
        permission: true,
        tooltip: 'View Tree',
        spinner: false,
        enabledFor: ['**.present.**'],
    },
    {
        id: 'tree-of-tables',
        icon: 'fa-table',
        selected: false,
        active: false,
        permission: true,
        tooltip: 'Table of Tables',
        spinner: false,
        enabledFor: ['**.present.**'],
    },
    {
        id: 'tree-of-figures',
        icon: 'fa-image',
        selected: false,
        active: false,
        permission: true,
        tooltip: 'Table of Figures',
        spinner: false,
        enabledFor: ['**.present.**'],
    },
    {
        id: 'tree-of-equations',
        icon: 'fa-superscript',
        selected: false,
        active: false,
        permission: true,
        tooltip: 'Table of Equations',
        spinner: false,
        enabledFor: ['**.present.**'],
    },
]

export const trees_dynamic_toolbar: IToolBarButton[] = []

export const trees_default_buttons: IButtonBarButton[] = [
    {
        id: 'tree-expand',
        icon: 'fa-regular fa-caret-square-down',
        selectable: true,
        permission: true,
        tooltip: 'Expand All',
        spinner: false,
        toggleable: false,
        placement: 'bottom-left',
    },
    {
        id: 'tree-collapse',
        icon: 'fa-regular fa-caret-square-up',
        selectable: true,
        permission: true,
        tooltip: 'Collapse All',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'tree-filter',
        icon: 'fa-solid fa-filter',
        selectable: true,
        permission: true,
        tooltip: 'Filter',
        spinner: false,
        toggleable: true,
    },
    {
        id: 'tree-add',
        icon: 'fa-solid fa-plus',
        selectable: true,
        permission: false,
        tooltip: 'Add Group or Document',
        spinner: false,
        toggleable: false,
        placement: 'bottom-right',
        dropdown_ids: [
            'tree-add.group',
            'tree-add.document',
            'tree-add.view',
            'tree-add.tag',
        ],
    },
    {
        id: 'tree-add.view',
        icon: 'fa-solid fa-plus',
        active: false,
        selectable: false,
        permission: false,
        tooltip: 'Add View',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'tree-add.group',
        icon: 'fa-solid fa-folder',
        active: false,
        selectable: false,
        permission: false,
        tooltip: 'Add Group',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'tree-clear-select',
        icon: 'fa-regular fa-folder',
        selectable: false,
        permission: true,
        tooltip: 'Clear Selection',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'tree-add.document',
        icon: 'fa-solid fa-file',
        active: false,
        selectable: false,
        permission: false,
        tooltip: 'Add Document',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'tree-refresh',
        icon: 'fa-solid fa-refresh',
        selectable: false,
        permission: true,
        tooltip: 'Refresh Tree Data',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'tree-add.tag',
        icon: 'fa-solid fa-tag',
        active: false,
        selectable: false,
        permission: false,
        tooltip: 'Add Tag',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'tree-add.branch',
        icon: 'fa-solid fa-plus',
        active: false,
        selectable: false,
        permission: false,
        tooltip: 'Add Branch',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'tree-delete',
        icon: 'fa-solid fa-trash',
        selectable: false,
        permission: false,
        tooltip: 'Remove',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'tree-reorder-view',
        icon: 'fa-solid fa-arrows-v',
        selectable: false,
        permission: false,
        tooltip: 'Reorder Views',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'tree-reorder-group',
        icon: 'fa-solid fa-arrows-v',
        selectable: false,
        permission: false,
        tooltip: 'Organize Groups/Docs',
        spinner: false,
        toggleable: false,
    },
    {
        id: 'tree-full-document',
        icon: 'fa-regular fa-file-text',
        selectable: false,
        permission: true,
        tooltip: 'Full Document',
        spinner: false,
        toggleable: true,
        toggle_tooltip: 'View Mode',
    },
    {
        id: 'tree-show-pe',
        icon: 'fa-regular fa-image',
        selected: false,
        selectable: false,
        permission: true,
        tooltip: 'Show PE',
        spinner: false,
        toggleable: true,
        toggle_tooltip: 'Hide PE',
    },
]
