import { IButtonBarButton } from '@ve-core/button-bar';

export const pane_center_buttons: IButtonBarButton[] = [
    {
        buttonId: 'share-page',
        icon: 'fa-solid fa-arrow-up-from-bracket',
        selectable: false,
        toggleable: false,
        tooltip: 'Share Page',
        title: 'Link',
        templateUrl: 'shareUrlTemplate.html',
        className: 'share-link',
    },
    {
        buttonId: 'show-edits',
        icon: 'fa-regular fa-pen-to-square',
        selectable: false,
        toggleable: true,
        tooltip: 'Enable Edits (alt + d)',
        toggledTooltip: 'Disable Edits (alt + d)',
    },
    {
        buttonId: 'show-elements',
        icon: 'fa-brands fa-codepen',
        selectable: false,
        toggleable: true,
        tooltip: 'Show Elements (alt + e)',
        toggledTooltip: 'Hide Elements (alt + e)',
    },
    {
        buttonId: 'show-comments',
        icon: 'fa-regular fa-comment',
        selectable: false,
        toggleable: true,
        tooltip: 'Show Comments (alt + c)',
        toggledTooltip: 'Hide Comments (alt + c)',
    },
    {
        buttonId: 'show-numbering',
        icon: 'fa-solid fa-list-ol',
        selectable: false,
        toggleable: true,
        tooltip: 'Show Numbering',
        toggledTooltip: 'Hide Numbering',
        disabledFor: ['**.portal.**'],
    },
    {
        buttonId: 'refresh-numbering',
        icon: 'fa-solid fa-sort-numeric-asc',
        selectable: false,
        spinnable: true,
        tooltip: 'Refresh Figure Numbering',
    },
    {
        buttonId: 'share-url',
        icon: 'fa-solid fa-arrow-up-right-from-square',
        selectable: false,
        tooltip: 'Share Short URL',
    },
    {
        buttonId: 'center-previous',
        icon: 'fa-solid fa-chevron-left',
        selectable: false,
        spinnable: true,
        tooltip: 'Previous (alt + ,)',
    },
    {
        buttonId: 'center-next',
        icon: 'fa-solid fa-chevron-right',
        selectable: false,
        spinnable: true,
        tooltip: 'Next (alt + .)',
    },
    {
        buttonId: 'export',
        icon: 'fa-solid fa-download',
        selectable: false,
        tooltip: 'Export',
        label: true,
        title: 'Export',
        toggleable: true,
        dropdownIds: ['convert-pdf', 'word', 'tabletocsv'],
    },
    {
        buttonId: 'print',
        icon: 'fa-solid fa-print',
        selectable: false,
        tooltip: 'Print',
    },
    {
        buttonId: 'convert-pdf',
        icon: 'fa-regular fa-file-pdf',
        selectable: false,
        tooltip: 'Export to PDF',
    },
    {
        buttonId: 'word',
        icon: 'fa-regular fa-file-word',
        selectable: false,
        tooltip: 'Export to Word',
    },
    {
        buttonId: 'tabletocsv',
        icon: 'fa-solid fa-table',
        selectable: false,
        tooltip: 'Table to CSV',
    },
];
